#' Generator of Random Walk
#' @param steps - Number of steps of the random walk
#' @param prob - Probability of occurence of head and tails for each step
#' @param n - Number of random walk generated by the function
#' @examples
#' adaptedSampledRandomWalkGenerator(n = 100)
#' It returns 100 data.frames with adapted stochastic process (Random Walk in this)
#' @references
#' [1] Symmetric Random Walk, Stochastic Calculus for Finance, Steven e. Shreve, 2004, pp 83-84
#' @export
adaptedSampledRandomWalk <- function(steps = 3000,
                                     prob = c('head' = 0.5,
                                              'tail' = 0.5)){
  adaptedSampledRandomWalkGenerator(steps, prob, 1)[[1]]
}
