 #' Generator of Random Walk
#' @param steps - Number of steps of the random walk
#' @param prob - Probability of occurence of head and tails for each step
#' @param n - Number of random walk generated by the function
#' @examples
#' adaptedSampledRandomWalkGenerator(n = 100)
#' It returns 100 data.frames with adapted stochastic process (Random Walk in this case)
#' @references
#' [1] Symmetric Random Walk, Stochastic Calculus for Finance, Steven e. Shreve, 2004, pp 83-84
#' @export
adaptedSampledRandomWalkGenerator <- function(steps = 3000,
                                              prob = c('head' = 0.5,
                                                       'tail' = 0.5),
                                              n = 1){
  randomWalkSampled <- randomWalkGenerator(steps, prob, n)
  lapply(randomWalkSampled, function(x){data.frame(0:(length(x) - 1), x)})
 }
