#' Generator of symmetric random walk sampled n times.
#' We call this random walk symmetric because the probability of head and tail
#' are equal. Both of them equal one half.
#' @param steps - Number of steps of the random walk
#' @param prob - Probability of occurence of head and tail for each step
#' @param n - Number of sample generated by the function
#' @examples
#' # Generate 20 samples of a symmetric random walk
#' sampledSymmetricRandomWalkGenerator(n = 20)
#' @references
#' [1] Symmetric Random Walk, Stochastic Calculus for Finance, Steven e. Shreve, 2004, pp 83-84
#' @export
sampledSymmetricRandomWalkGenerator <- function(steps = 3000,
                                prob = c('head' = 0.5, 'tail' = 0.5),
                                n = 1){

  x <- rep(list(c(-1, 1)), n)

  X <- lapply(x,
              sample,
              size = steps,
              replace = T,
              prob = prob)

  (Mk <- lapply(X, function(i){
    c(0,
      sapply(seq_along(i),
             function(x){
               sum(i[1:x])
             }))
  })
  )
  as.data.frame(Mk)
}
