#' Generator of Random Walk
#' @param steps - Number of steps of the random walk
#' @param prob - Probability of occurence of head and tails for each step
#' @param n - Number of random walk generated by the function
#' @examples
#' randomWalkGenerator(n = 100)
#' @references
#' [1] Symmetric Random Walk, Stochastic Calculus for Finance, Steven e. Shreve, 2004, pp 83-84
#' @export
sampledRandomWalkGenerator <- function(steps = 3000,
                                prob = c('head' = 0.5, 'tail' = 0.5),
                                n = 1){

  x <- rep(list(c(-1, 1)), n)

  X <- lapply(x,
              sample,
              size = steps,
              replace = T,
              prob = prob)

  (Mk <- lapply(X, function(i){
    c(0,
      sapply(seq_along(i),
             function(x){
               sum(i[1:x])
             }))
  })
  )
  (as.data.frame(Mk))
}
