#' Generates a list of symmetric random walk sampled n times along with its time periods.
#' The time period goes from 0 up to T (0: time_to_maturity), for each sample.
#' It corresponds to a single random walk's path with each of its associated time period.
#' @param time_to_maturity - Number of time_to_maturity of the random walk
#' @param prob - Probability of occurence of head and tail for each step
#' @param n - Number of sample generated by the function
#' @examples
#' # Generate a list of 20 sampled symmetric random walks
#' adaptedSampledSymmetricRandomWalkGenerator(n = 20)
#' @references
#' [1] Symmetric Random Walk, Stochastic Calculus for Finance, Steven e. Shreve, 2004, pp 83-84
#' @export
srwalkGenerator <- function(time_to_maturity = 100,
                            prob = c('head' = 0.5,
                                     'tail' = 0.5),
                            scale = 1,
                            n = 1){

  # set the whole time step ----------------------------
  # The following has just to be set up once because it is the same one that
  # is used for all the random walk. Because all are indeed a different sample
  # of the same random walk.
  # TODO rename step -> partition
  step <- seq(from = 0,
              to = time_to_maturity,
              by = 1/scale)

  # All index (step * n) must be integer. Even it is probably not the optimal
  # way, I will round the value to get a sure integer value for (step * n)
  # step <- round(step * 100) / 100

  # Define the path constant multiplier ----------------------------
  multiplier <- 1 / sqrt(scale)

  # Construction of the random variable ----------------------------

  x <- rep(list(c(-1, 1)), n)

  X <- lapply(x,
              sample,
              size = time_to_maturity * scale,
              replace = T,
              prob = prob)

  Mk <- lapply(X, function(i){
    c(0,
      sapply(seq_along(i),
             function(x){
               sum(i[1:x]) * multiplier
             })
    )})

  sampledRandomWalk <- as.data.frame(Mk)

  # Construction of the x-axis ----------------------------
  # Based on the step variable, we get the x-axis for all different path
  # of the scaled random walk

  rwalkFactory <- function(x){
    a <- data.frame(step, x)
    class(a) <- c(class(a), "randomwalk")
    names(a) <- c('time_periods', 'random_walk_path')
    a
  }

  lapply(sampledRandomWalk, rwalkFactory )

}
