#' Generates a list of symmetric random walk sampled n times along with its time periods.
#' The time period goes from 0 up to T (0: steps), for each sample.
#' It corresponds to a single random walk's path with each of its associated time period.
#' @param steps - Number of steps of the random walk
#' @param prob - Probability of occurence of head and tail for each step
#' @param n - Number of sample generated by the function
#' @examples
#' # Generate a list of 20 sampled symmetric random walks
#' adaptedSampledSymmetricRandomWalkGenerator(n = 20)
#' @references
#' [1] Symmetric Random Walk, Stochastic Calculus for Finance, Steven e. Shreve, 2004, pp 83-84
#' @export
srwalkGenerator <- function(steps = 100,
                            prob = c('head' = 0.5,
                                     'tail' = 0.5),
                            n = 1){

  x <- rep(list(c(-1, 1)), n)

  X <- lapply(x,
              sample,
              size = steps,
              replace = T,
              prob = prob)

  Mk <- lapply(X, function(i){
    c(0,
      sapply(seq_along(i),
             function(x){
               sum(i[1:x])
             })
    )})

  sampledRandomWalk <- as.data.frame(Mk)
  (
  lapply(sampledRandomWalk, function(x){data.frame(0:(length(x) - 1), x)})
  )
}
