#' @title A generator of sample random walks
#'
#'
#' @description It generates a zoo object of sample scaled Random Walks
#' along with the associated time periods.
#' Time period goes from  `start` to `stop`. If no stop date is provided,
#' it is computed based on the argument `tau`, such as:
#' `stop` <- `start` + `tau`, with `tau` expressed in days.
#'
#'
#' @inheritParams trwalk
#' @param seed  An integer. With same seed, 2 exeriments will give the same
#' output. It therefore provides reproducible experiments.
#' @param n  An integer. Number of samples generated by the function.
#'
#'
#' @examples
#' # Generate a zoo object of 20 sampled symmetric random walks ordered by date
#' # from today and up to the next 360 upcoming days
#' srwalk(n = 20)
#'
#'
#' @return \code{srwalk()} output a zoo object containing some random walks.
#' The so generated random walks are independent and indentically distributed.
#' All share the same start and stop date.
#'
#'
#' @references
#' [1] Symmetric Random Walk, Stochastic Calculus for Finance, Steven e. Shreve, 2004, pp 83-84
#'
#'
#' @export
srwalk <- function(start = Sys.Date(),
                   tau = 365,
                   stop = F,
                   prob = c('head' = 0.5, 'tail' = 0.5),
                   interval = 'day',
                   seed = 1,
                   n = 1){

  set.seed(seed)
  if (!lubridate::is.Date(stop))
    stop <- start + tau

  # set the whole time partition ----------------------------
  partition <- seq(from = start,
                   to = stop,
                   by = interval)


  # Define the multiplier ----------------------------
  # The multiplier is equal to sqrt of time in order to get a normal distribution
  # with expectation of zero (defined by the symmetry of head and tail probability)
  # and a standard deviation of square root of time (defined by the multiplier)
  multiplier <- sqrt(as.numeric(diff(partition)))

  # Construction of the random variable ----------------------------
  x <- rep(list(c(-1, 1)), n)

  X <- lapply(x, sample,
              size = length(multiplier),
              replace = T,
              prob = prob)

  # c(0, ...) because the initial value of a random walk is zero.
  sampledRandomWalk <- structure(purrr::map(X, ~c(0, cumsum(.x) * multiplier)),
                                 names = 1:length(X))

  # Construction the time series objects ----------------------------
  randomwalk <- zoo::zoo(
    tibble::as.tibble(sampledRandomWalk), order.by = partition
  )

  # Return the object ----------------------------
  randomwalk
}
