#' @title A generator of sample random walks
#'
#'
#' @description It generates a zoo object of sample scaled Random Walks
#' along with the associated time periods.
#' Time period goes from  `from` to `stop`. If no stop date is provided,
#' it is computed based on the argument `to`, such as:
#' `stop` <- `from` + `to`, with `to` expressed in days.
#'
#'
#' @inheritParams trwalk
#' @param seed  An integer. With same seed, 2 exeriments will give the same
#' output. It therefore provides reproducible experiments.
#' @param n  An integer. Number of samples generated by the function.
#'
#'
#' @examples
#' # Generate a zoo object of 20 sampled symmetric random walks ordered by date
#' # from today and up to the next 360 upcoming days
#' srwalk(n = 20)
#'
#'
#' @return \code{srwalk()} output a zoo object containing some random walks.
#' The so generated random walks are independent and indentically distributed.
#' All share the same from and stop date.
#'
#'
#' @references
#' [1] Symmetric Random Walk, Stochastic Calculus for Finance, Steven e. Shreve, 2004, pp 83-84
#'
#'
#' @export

srwalk <- function(from = Sys.Date(),
                   to,
                   len = 365,
                   prob = .5,
                   interval = 'day',
                   seed = 1,
                   n = 1){

  set.seed(seed)
  if (missing(to)) to <- from + len

  partition <- seq(from = from,
                   to = to,
                   by = interval)

  multiplier <- sqrt(as.numeric(diff(partition)))

  # 1: head, -1: tail
  x <- rep(list(c(1, -1)), n)

  X <- lapply(x, sample,
              size = length(multiplier),
              replace = T,
              prob = c(prob, 1-prob))

  sampledRandomWalk <- structure(
    lapply(X, FUN = function(x){c(0, cumsum(x) * multiplier)}),
    names = paste0("P",
                   stringr::str_pad(1:length(X),
                                    width = length(X),
                                    pad = "0"))
  )

  zoo::zoo(data.frame(sampledRandomWalk), order.by = partition)
}
